[project]
org-name= "isuru"
version= "0.1.0"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "abc"
    path = "/Users/isuru/.m2/repository/mysql/mysql-connector-java/8.0.11/mysql-connector-java-8.0.11.jar"
    #path = "/home/wso2/.m2/repository/mysql/mysql-connector-java/8.0.12/mysql-connector-java-8.0.12.jar"
    groupId = "abc"
    modules = ["db_acces", "db_read"]
